shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.cd-gitroot]
github = "mollifier/cd-gitroot"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-poetry]
github = "darvid/zsh-poetry"
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
